export const KNOWLEDGE_BASE_MAX_FILE_SIZE = 50 * 1024 * 1024
export const KNOWLEDGE_BASE_MAX_FILE_SIZE_LABEL = '50 MB'
export const KNOWLEDGE_BASE_MAX_PARSED_CONTENT_SIZE = 20 * 1024 * 1024
export const KNOWLEDGE_BASE_MAX_PARSED_CONTENT_SIZE_LABEL = '20 MB'
export const KNOWLEDGE_BASE_PARSED_CONTENT_TOO_LARGE_ERROR = 'knowledge_base_parsed_content_too_large'
