export const JK_EVENTS = {
  ONBOARDING_CHOICE_CLICK: 'onboarding_choice_click',
  LOGIN_BUTTON_CLICK: 'login_button_click',
  FREE_LICENSE_CLAIM_CLICK: 'free_license_claim_click',
  KEY_VERIFY_SUCCESS: 'key_verify_success',
  KEY_VERIFY_FAILED: 'key_verify_failed',
  APP_LAUNCH: 'app_launch',
  PAGE_VIEW: 'page_view',
  PREVIEW_WEBPAGE_CLICK: 'preview_webpage_click',
  COPY_CODE_CLICK: 'copy_code_click',
  LIST_MODEL_CLICK: 'list_model_click',
  SELECT_MODEL_CLICK: 'select_model_click',
  UPGRADE_MODEL_CLICK: 'upgrade_model_click',
  LEAD_CHAT_CARD_CLICK: 'lead_chat_card_click',
  AGENT_MODE_SELECT: 'agent_mode_select',
  SMART_SWITCHING_CLICK: 'smart_switching_click',
  CODE_EXECUTION_CLICK: 'code_execution_click',
  WORK_MODE_SUGGEST: 'work_mode_suggest',
  WORK_MODE_SUGGESTION_ACT: 'work_mode_suggestion_act',
  WEB_SEARCH_CLICK: 'web_search_click',
  WORK_MODE_PAUSE_ACT: 'work_mode_pause_act',
  AGENT_MODE_FREE_POINTS_CARD: 'agent_mode_free_points_card',
  AGENT_MODE_FREE_POINTS_CARD_CLICK: 'agent_mode_free_points_card_click',
  AGENT_MODE_FREE_POINTS_CLAIM_SUCCESS: 'agent_mode_free_points_claim_success',
  MERMAID_RENDER_FAILED: 'mermaid_render_failed',
} as const

export const JK_PAGE_NAMES = {
  CHAT_PAGE: 'chat_page',
  SETTING_PAGE: 'setting_page',
  IMAGE_PAGE: 'image_page',
  COPILOTS_PAGE: 'copilots_page',
  HELP_PAGE: 'help_page',
  ABOUT_PAGE: 'about_page',
} as const
