/**
 * Build-time script to generate a models.dev snapshot.
 *
 * Fetches https://models.dev/api.json, filters to mapped providers,
 * transforms to ModelRegistryData format, and writes to
 * src/shared/model-registry/snapshot.generated.ts.
 *
 * Usage: npx tsx scripts/generate-model-snapshot.ts
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import { PROVIDER_ID_MAP, REVERSE_PROVIDER_MAP } from '../src/shared/model-registry/provider-mapping'
import { transformModelEntry } from '../src/shared/model-registry/transform'
import type { ModelMetadata, ModelsDevModelEntry } from '../src/shared/model-registry/types'

const API_URL = 'https://models.dev/api.json'
const FETCH_TIMEOUT_MS = 15_000
const OUTPUT_PATH = path.resolve(__dirname, '../src/shared/model-registry/snapshot.generated.ts')

async function main() {
  console.log('[model-snapshot] Fetching models.dev API...')

  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS)

  let response: Response
  try {
    response = await fetch(API_URL, { signal: controller.signal })
  } finally {
    clearTimeout(timeout)
  }
  if (!response.ok) {
    throw new Error(`Failed to fetch models.dev: ${response.status} ${response.statusText}`)
  }

  const data: unknown = await response.json()
  if (typeof data !== 'object' || data === null) {
    throw new Error(`Unexpected API response: expected object, got ${typeof data}`)
  }

  const registry: Record<string, Record<string, ModelMetadata>> = {}
  let totalModels = 0

  for (const [modelsDevId, providerEntry] of Object.entries(data)) {
    const chatboxIds = REVERSE_PROVIDER_MAP[modelsDevId]
    if (!chatboxIds || chatboxIds.length === 0) continue

    const provider = providerEntry as { models?: Record<string, ModelsDevModelEntry> }
    if (!provider.models || typeof provider.models !== 'object') continue

    const providerModels: Record<string, ModelMetadata> = {}
    for (const [modelId, entry] of Object.entries(provider.models)) {
      if (!entry || !modelId) continue
      providerModels[modelId] = transformModelEntry(entry)
      totalModels++
    }

    for (const chatboxId of chatboxIds) {
      registry[chatboxId] = providerModels
    }
  }

  const timestamp = new Date().toISOString()
  const providerCount = new Set(Object.values(PROVIDER_ID_MAP)).size

  const output = `// Auto-generated by scripts/generate-model-snapshot.ts
// Generated at: ${timestamp}
// Source: ${API_URL}
//
// DO NOT EDIT THIS FILE MANUALLY.
// Run: pnpm generate:model-snapshot

import type { ModelRegistryData } from './types'

export const SNAPSHOT_TIMESTAMP = '${timestamp}'

export const MODELS_DEV_SNAPSHOT: ModelRegistryData = ${JSON.stringify(registry, null, 2)} as const satisfies ModelRegistryData
`

  fs.writeFileSync(OUTPUT_PATH, output, 'utf-8')

  const fileSizeKB = Math.round(fs.statSync(OUTPUT_PATH).size / 1024)
  console.log(`[model-snapshot] Generated snapshot:`)
  console.log(`  Providers: ${providerCount} (mapped to ${Object.keys(registry).length} Chatbox IDs)`)
  console.log(`  Models: ${totalModels}`)
  console.log(`  File size: ${fileSizeKB} KB`)
  console.log(`  Output: ${OUTPUT_PATH}`)
}

main().catch((err) => {
  console.error('[model-snapshot] Failed:', err)
  process.exit(1)
})
